# Generated by Django 4.1.3 on 2022-12-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='session_id',
            new_name='session_year_id',
        ),
    ]
